### ISSUE TITLE
download daily data has error

### ISSUE THREAD

**Issue by nsheils** [GeoDS/COVID19USFlows#5]
Line 25 of the download_daily_data.py file should be: 

start_year = str(args.start_year).zfill(4)

**Comment by kkyyhh96** [comment]
Hi @nsheils ,

Thanks for pointing it out. We have fixed the bug accordingly. Thanks for your prompt help!

In addition, we are updating our repository to a new version. The new repository will be ready in 2 days. That is why the 2020/12/31 data is missing. You can go back and check our repository on Saturday. 

Thank you for using our dataset!
