### ISSUE TITLE
One error found in codes/download_daily_data.py

### ISSUE THREAD

**Issue by august-zhu** [GeoDS/COVID19USFlows#7]
I was trying to download the `ct2ct` daily data and found this error.

In `codes/download_daily_data.py`, there is an error in line 54:
`os.mkdir(f"{output_folder}/{scale}/{month}_{day}/")`

And the `year` is missing when creating the folder. It should be:
`os.mkdir(f"{output_folder}/{scale}/{year}_{month}_{day}/")`

so that when you run line 63 `with open(f"{output_folder}/{scale}/{year}_{month}_{day}/daily_{scale}_{year}_{month}_{day}_{i}.csv", 'wb') as file:`, it won't report error of `No such file or directory`.

**Comment by kkyyhh96** [comment]
Thank you so much for reporting it! We will fix it accordingly.

**Comment by kkyyhh96** [comment]
@august-zhu Thank you so much for reporting it! We will fix it accordingly.
