### ISSUE TITLE
Some dates of the daily ct2ct files are not available.

### ISSUE THREAD

**Issue by Haiyan-Hao** [GeoDS/COVID19USFlows#9]
Hello, thanks very much for sharing the data. I am intending to use the data for my research. I found that some daily ct2ct flows in 2019 are not available, which mostly for the last one or two day of a month (e.g., 8/30/2019, 8/31/2019, 9/30/2019, 10/30/2019, and the whole November and December data for ct2ct flows in 2019).

**Comment by kkyyhh96** [comment]
Hi Haiyan,

Thanks for reaching out to us. Currently, GitHub said that our repository is over its quota due to the large data size. We are still working on solving it. I will let you know when we fix this issue.

**Comment by Haiyan-Hao** [comment]
Hi, I found the new repositories that you upload the data. Thanks a lot!
